### Deployments and Jobs

# Insurance CA
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: insurance-ca
spec:
  template:
    metadata:
      labels:
        app: insurance-ca
        type: ca
    spec:
      containers:
      - name: insurance-ca
        image: registry.eu-de.bluemix.net/bcins/insurance-ca:latest
        command: ["fabric-ca-server"]
        args: ["start"]
        ports:
        - containerPort: 7054
        env:
        - name: FABRIC_CA_HOME
          value: /ca
        - name: GODEBUG
          value: netdns=go

# Shop CA
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shop-ca
spec:
  template:
    metadata:
      labels:
        app: shop-ca
        type: ca
    spec:
      containers:
      - name: shop-ca
        image: registry.eu-de.bluemix.net/bcins/shop-ca:latest
        command: ["fabric-ca-server"]
        args: ["start"]
        ports:
        - containerPort: 7054
        env:
        - name: FABRIC_CA_HOME
          value: /ca
        - name: GODEBUG
          value: netdns=go

# Repair Shop CA
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: repairshop-ca
spec:
  template:
    metadata:
      labels:
        app: repairshop-ca
        type: ca
    spec:
      containers:
      - name: repairshop-ca
        image: registry.eu-de.bluemix.net/bcins/repairshop-ca:latest
        command: ["fabric-ca-server"]
        args: ["start"]
        ports:
        - containerPort: 7054
        env:
        - name: FABRIC_CA_HOME
          value: /ca
        - name: GODEBUG
          value: netdns=go

# Police CA
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: police-ca
spec:
  template:
    metadata:
      labels:
        app: police-ca
        type: ca
    spec:
      containers:
      - name: repairshop-ca
        image: registry.eu-de.bluemix.net/bcins/police-ca:latest
        command: ["fabric-ca-server"]
        args: ["start"]
        ports:
        - containerPort: 7054
        env:
        - name: FABRIC_CA_HOME
          value: /ca
        - name: GODEBUG
          value: netdns=go

# Orderer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orderer0
spec:
  template:
    metadata:
      labels:
        app: orderer0
        type: orderer
    spec:
      containers:
      - name: orderer0
        image: registry.eu-de.bluemix.net/bcins/orderer:latest
        command: ["orderer"]
        ports:
        - containerPort: 7050
        workingDir: /orderer
        env:
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /orderer/crypto/genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /orderer/crypto/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /orderer/crypto/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /orderer/crypto/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: "[/orderer/crypto/tls/ca.crt]"
        - name: GODEBUG
          value: netdns=go

# Insurace Peer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: insurance-peer
spec:
  template:
    metadata:
      labels:
        app: insurance-peer
        type: peer
    spec:
      volumes:
      - name: docker-internals
        hostPath:
          path: /var/run/
      containers:
      - name: insurance-peer
        image: registry.eu-de.bluemix.net/bcins/insurance-peer:latest
        command: ["peer"]
        args: ["node", "start"]
        ports:
        - containerPort: 7051
        - containerPort: 7053
        workingDir: /peer
        volumeMounts:
        - name: docker-internals
          mountPath: /host/var/run/
        env:
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_VM_DOCKER_HOSTCONFIG_DNS
          value: 10.10.10.10
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
          value: bridge
        - name: CORE_VM_DOCKER_HOSTCONFIG_DNSSEARCH
          value: default.svc.cluster.local
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_TLS_ENABLED
          value: "true" 
        - name: CORE_PEER_ENDORSER_ENABLED
          value: "true" 
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true" 
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false" 
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true" 
        - name: CORE_PEER_MSPCONFIGPATH
          value: /peer/crypto/msp
        - name: CORE_PEER_TLS_CERT_FILE
          value: /peer/crypto/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /peer/crypto/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /peer/crypto/tls/ca.crt
        - name: CORE_PEER_ID
          value: insurance-peer
        - name: CORE_PEER_ADDRESS
          value: insurance-peer:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: insurance-peer:7051
        - name: CORE_PEER_LOCALMSPID
          value: InsuranceOrgMSP
        - name: GODEBUG
          value: netdns=go

# Shop Peer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shop-peer
spec:
  template:
    metadata:
      labels:
        app: shop-peer
        type: peer
    spec:
      volumes:
      - name: docker-internals
        hostPath:
          path: /var/run/
      containers:
      - name: shop-peer
        image: registry.eu-de.bluemix.net/bcins/shop-peer:latest
        command: ["peer"]
        args: ["node", "start"]
        ports:
        - containerPort: 7051
        - containerPort: 7053
        workingDir: /peer
        volumeMounts:
        - name: docker-internals
          mountPath: /host/var/run/
        env:
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_VM_DOCKER_HOSTCONFIG_DNS
          value: 10.10.10.10
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
          value: bridge
        - name: CORE_VM_DOCKER_HOSTCONFIG_DNSSEARCH
          value: default.svc.cluster.local
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_TLS_ENABLED
          value: "true" 
        - name: CORE_PEER_ENDORSER_ENABLED
          value: "true" 
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true" 
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false" 
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true" 
        - name: CORE_PEER_MSPCONFIGPATH
          value: /peer/crypto/msp
        - name: CORE_PEER_TLS_CERT_FILE
          value: /peer/crypto/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /peer/crypto/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /peer/crypto/tls/ca.crt
        - name: CORE_PEER_ID
          value: shop-peer
        - name: CORE_PEER_ADDRESS
          value: shop-peer:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: shop-peer:7051
        - name: CORE_PEER_LOCALMSPID
          value: ShopOrgMSP
        - name: GODEBUG
          value: netdns=go

# Repair Shop Peer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: repairshop-peer
spec:
  template:
    metadata:
      labels:
        app: repairshop-peer
        type: peer
    spec:
      volumes:
      - name: docker-internals
        hostPath:
          path: /var/run/
      containers:
      - name: repairshop-peer
        image: registry.eu-de.bluemix.net/bcins/repairshop-peer:latest
        command: ["peer"]
        args: ["node", "start"]
        ports:
        - containerPort: 7051
        - containerPort: 7053
        workingDir: /peer
        volumeMounts:
        - name: docker-internals
          mountPath: /host/var/run/
        env:
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_VM_DOCKER_HOSTCONFIG_DNS
          value: 10.10.10.10
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
          value: bridge
        - name: CORE_VM_DOCKER_HOSTCONFIG_DNSSEARCH
          value: default.svc.cluster.local
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_TLS_ENABLED
          value: "true" 
        - name: CORE_PEER_ENDORSER_ENABLED
          value: "true" 
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true" 
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false" 
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true" 
        - name: CORE_PEER_MSPCONFIGPATH
          value: /peer/crypto/msp
        - name: CORE_PEER_TLS_CERT_FILE
          value: /peer/crypto/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /peer/crypto/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /peer/crypto/tls/ca.crt
        - name: CORE_PEER_ID
          value: repairshop-peer
        - name: CORE_PEER_ADDRESS
          value: repairshop-peer:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: repairshop-peer:7051
        - name: CORE_PEER_LOCALMSPID
          value: RepairShopOrgMSP
        - name: GODEBUG
          value: netdns=go

# Police Peer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: police-peer
spec:
  template:
    metadata:
      labels:
        app: police-peer
        type: peer
    spec:
      volumes:
      - name: docker-internals
        hostPath:
          path: /var/run/
      containers:
      - name: police-peer
        image: registry.eu-de.bluemix.net/bcins/police-peer:latest
        command: ["peer"]
        args: ["node", "start"]
        ports:
        - containerPort: 7051
        - containerPort: 7053
        workingDir: /peer
        volumeMounts:
        - name: docker-internals
          mountPath: /host/var/run/
        env:
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_VM_DOCKER_HOSTCONFIG_DNS
          value: 10.10.10.10
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
          value: bridge
        - name: CORE_VM_DOCKER_HOSTCONFIG_DNSSEARCH
          value: default.svc.cluster.local
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_TLS_ENABLED
          value: "true" 
        - name: CORE_PEER_ENDORSER_ENABLED
          value: "true" 
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true" 
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false" 
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true" 
        - name: CORE_PEER_MSPCONFIGPATH
          value: /peer/crypto/msp
        - name: CORE_PEER_TLS_CERT_FILE
          value: /peer/crypto/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /peer/crypto/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /peer/crypto/tls/ca.crt
        - name: CORE_PEER_ID
          value: police-peer
        - name: CORE_PEER_ADDRESS
          value: police-peer:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: police-peer:7051
        - name: CORE_PEER_LOCALMSPID
          value: PoliceOrgMSP
        - name: GODEBUG
          value: netdns=go

# Web Frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-frontend
spec:
  template:
    metadata:
      labels:
        app: web-frontend
        type: frontend
    spec:
      volumes:
      - name: docker-internals
        hostPath:
          path: /var/run/
      containers:
      - name: web-frontend
        image: registry.eu-de.bluemix.net/bcins/web:latest
        env:
        - name: PORT
          value: "3000"
        - name: DOCKER_SOCKET_PATH
          value: /host/var/run/docker.sock
        - name: DOCKER_CCENV_IMAGE
          value: hyperledger/fabric-ccenv:x86_64-1.0.2
        volumeMounts:
        - name: docker-internals
          mountPath: /host/var/run/
        ports:
        - containerPort: 3000

### Services

# Insurance CA
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-ca
spec:
  selector:
    app: insurance-ca
  ports:
  - protocol: TCP
    port: 7054
    targetPort: 7054

# Shop CA
---
apiVersion: v1
kind: Service
metadata:
  name: shop-ca
spec:
  selector:
    app: shop-ca
  ports:
  - protocol: TCP
    port: 7054
    targetPort: 7054


# Repair Service CA
---
apiVersion: v1
kind: Service
metadata:
  name: repairshop-ca
spec:
  selector:
    app: repairshop-ca
  ports:
  - protocol: TCP
    port: 7054
    targetPort: 7054

# Police CA
---
apiVersion: v1
kind: Service
metadata:
  name: police-ca
spec:
  selector:
    app: police-ca
  ports:
  - protocol: TCP
    port: 7054
    targetPort: 7054

# Orderer0
---
apiVersion: v1
kind: Service
metadata:
  name: orderer0
spec:
  selector:
    app: orderer0
  ports:
  - protocol: TCP
    port: 7050
    targetPort: 7050

# Insurance Peer
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-peer
spec:
  selector:
    app: insurance-peer
  ports:
  - name: requests
    protocol: TCP
    port: 7051
    targetPort: 7051
  - name: events
    protocol: TCP
    port: 7053
    targetPort: 7053

# Shop Peer
---
apiVersion: v1
kind: Service
metadata:
  name: shop-peer
spec:
  selector:
    app: shop-peer
  ports:
  - name: requests
    protocol: TCP
    port: 7051
    targetPort: 7051
  - name: events
    protocol: TCP
    port: 7053
    targetPort: 7053

# Repair Shop Peer
---
apiVersion: v1
kind: Service
metadata:
  name: repairshop-peer
spec:
  selector:
    app: repairshop-peer
  ports:
  - name: requests
    protocol: TCP
    port: 7051
    targetPort: 7051
  - name: events
    protocol: TCP
    port: 7053
    targetPort: 7053

# Police Peer
---
apiVersion: v1
kind: Service
metadata:
  name: police-peer
spec:
  selector:
    app: police-peer
  ports:
  - name: requests
    protocol: TCP
    port: 7051
    targetPort: 7051
  - name: events
    protocol: TCP
    port: 7053
    targetPort: 7053

# Web Frontend
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
spec:
  type: NodePort
  selector:
    app: web-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
